#!/bin/bash
# Version 1

kpackagetool5 -t KWin/WindowSwitcher -u package

# Tell KWin to reload the task switcher.
# https://github.com/KDE/kwin/blob/master/kcmkwin/kwintabbox/main.cpp#L375
# Note there's a slot connected to the reloadConfig() signal that calls reconfigure()
# qdbus org.kde.KWin /KWin reconfigure # Doesn't work

# Restart KWin
kwin_x11 --replace & disown
