#!/bin/bash
# Version 1

rm -r /home/chris/.local/share/kwin/tabbox/thumbnail_grid/
# plasmapkg2 -t windowswitcher -r package
plasmapkg2 -t windowswitcher -i package
# killall plasmashell
# kstart plasmashell
